- id: doi:10.1126/science.adh8697
  image: https://www.science.org/cms/asset/23c91113-5fc9-4da2-b16a-e7cb7e1f342a/science.2024.384.issue-6699.largecover.jpg
  category: 

- id: doi:10.1038/s41586-024-08377-x
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-024-08377-x/MediaObjects/41586_2024_8377_Fig1_HTML.png
  category: 

- id: doi:10.1093/nar/gkx1126
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/nar/Issue/46/D1/2/m_cover.gif?Expires=1744459365&Signature=g6NUrK6VKf1dcsBKINZe6ug45Z5UOL9w5COuRAuVNT36P2-zA-XPIYvgwozhHbKSfLx9KMU~QLnRTDrBQtXoqFmOL34beWHhE10xMb8gghA3LpVquyxlxrH5fQJ-375mPCmH0SOGjeMur8fxmcwaDvdVafKyTYtUhEKMMjpObkb84GEiv15rjg3TK5v3rQLq041QE0qdZm57OlDrfYIDXdv4p1rTR1iMAkqiaaUh~c2QkVVopPhjItKzn4hJo4tubmojbJwiFf-Srv9B9xWFH68jnn4b3wv5s7s~uH50GDuwzH9joTICTS7l1eECgluNsIMh4aV0Dx8mzDrbF7XY0Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1093/bioinformatics/btx804
  image: images/bioinformatics_cover.jpeg
  buttons:
    - type: source
      text: Source Code
      link: https://github.com/asntech/intervene
  tags:
    - open-source
    - software

- id: doi:10.1093/bioinformatics/btaa928
  image: images/bioinformatics_cover.jpeg
  buttons:
    - type: source
      text: Source Code
      link: https://github.com/asntech/intervene
  tags:
    - open-source
    - software

- id: doi:10.1093/nar/gkv1002
  type: paper
  description: dbSUPER is the first database of super-enhancers and Aziz's first publication
  date: 2016-01-04
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/nar/Issue/46/D1/2/m_cover.gif?Expires=1744459365&Signature=g6NUrK6VKf1dcsBKINZe6ug45Z5UOL9w5COuRAuVNT36P2-zA-XPIYvgwozhHbKSfLx9KMU~QLnRTDrBQtXoqFmOL34beWHhE10xMb8gghA3LpVquyxlxrH5fQJ-375mPCmH0SOGjeMur8fxmcwaDvdVafKyTYtUhEKMMjpObkb84GEiv15rjg3TK5v3rQLq041QE0qdZm57OlDrfYIDXdv4p1rTR1iMAkqiaaUh~c2QkVVopPhjItKzn4hJo4tubmojbJwiFf-Srv9B9xWFH68jnn4b3wv5s7s~uH50GDuwzH9joTICTS7l1eECgluNsIMh4aV0Dx8mzDrbF7XY0Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  buttons:
    - type: website
      link: https://asntech.org/dbsuper
  tags:
    - open-source
    - database

- id: doi:10.1101/109728
  remove: true

- id: ppr:PPR499801
  remove: true

- id: ppr:PPR480175
  remove: true

- id: doi:10.1101/2023.03.15.532870
  remove: true

- id: pmid:33135764
  remove: true

  
