- id: doi:10.1126/science.adh8697
  image: https://www.science.org/cms/10.1126/science.adh8697/asset/f88a067e-6fb6-49db-88d1-c022946f7fa2/assets/images/large/science.adh8697-fa.jpg
  category: 

- id: doi:10.1038/s41586-024-08377-x
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-024-08377-x/MediaObjects/41586_2024_8377_Fig1_HTML.png
  category: 

- id: doi:10.1093/nar/gkx1126
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/nar/Issue/46/D1/2/m_cover.gif?Expires=1744459365&Signature=g6NUrK6VKf1dcsBKINZe6ug45Z5UOL9w5COuRAuVNT36P2-zA-XPIYvgwozhHbKSfLx9KMU~QLnRTDrBQtXoqFmOL34beWHhE10xMb8gghA3LpVquyxlxrH5fQJ-375mPCmH0SOGjeMur8fxmcwaDvdVafKyTYtUhEKMMjpObkb84GEiv15rjg3TK5v3rQLq041QE0qdZm57OlDrfYIDXdv4p1rTR1iMAkqiaaUh~c2QkVVopPhjItKzn4hJo4tubmojbJwiFf-Srv9B9xWFH68jnn4b3wv5s7s~uH50GDuwzH9joTICTS7l1eECgluNsIMh4aV0Dx8mzDrbF7XY0Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1093/bioinformatics/btx804
  image: images/publications/bioinformatics_cover.jpeg
  buttons:
    - type: source
      text: Source Code
      link: https://github.com/asntech/intervene
  tags:
    - open-source
    - software

- id: doi:10.1038/s41586-023-06102-8
  image: https://www.biorxiv.org/content/biorxiv/early/2022/04/28/2022.04.09.487529/F1.large.jpg


- id: doi:10.1038/s41586-024-08377-x
  image: "https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41586-024-08377-x/MediaObjects/41586_2024_8377_Fig1_HTML.png"


- id: doi:10.1016/j.xpro.2022.101927
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666166722008073-fx1.jpg

- id: doi:10.1038/s41562-021-01067-y
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41562-021-01067-y/MediaObjects/41562_2021_1067_Fig1_HTML.png

- id: doi:10.1093/bioinformatics/btaa928
  image: images/publications/bioinformatics_cover.jpeg
  buttons:
    - type: source
      text: Source Code
      link: https://github.com/asntech/intervene
  tags:
    - open-source
    - software

- id: doi:10.1093/nar/gkv1002
  type: paper
  description: dbSUPER is the first database of super-enhancers and Aziz's first publication
  date: 2016-01-04
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/nar/Issue/46/D1/2/m_cover.gif?Expires=1744459365&Signature=g6NUrK6VKf1dcsBKINZe6ug45Z5UOL9w5COuRAuVNT36P2-zA-XPIYvgwozhHbKSfLx9KMU~QLnRTDrBQtXoqFmOL34beWHhE10xMb8gghA3LpVquyxlxrH5fQJ-375mPCmH0SOGjeMur8fxmcwaDvdVafKyTYtUhEKMMjpObkb84GEiv15rjg3TK5v3rQLq041QE0qdZm57OlDrfYIDXdv4p1rTR1iMAkqiaaUh~c2QkVVopPhjItKzn4hJo4tubmojbJwiFf-Srv9B9xWFH68jnn4b3wv5s7s~uH50GDuwzH9joTICTS7l1eECgluNsIMh4aV0Dx8mzDrbF7XY0Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  buttons:
    - type: website
      link: https://asntech.org/dbsuper
  tags:
    - open-source
    - database

- id: doi:10.1093/nar/gkad1059
  image: images/publications/jaspar.jpeg
  buttons:
    - type: website
      text: JASPAR
      link: https://jaspar.elixir.no/


- id: doi:10.1093/nar/gkab1113
  image: images/publications/jaspar.jpeg
  buttons:
    - type: website
      text: JASPAR 2022
      link: https://jaspar2022.genereg.net/


# Remove the following duplicates

- id: doi:10.1101/109728
  remove: true

- id: ppr:PPR499801
  remove: true

- id: ppr:PPR480175
  remove: true

- id: doi:10.1101/2023.03.15.532870
  remove: true

- id: pmid:33135764
  remove: true

- id: pmid:36586123
  remove: true

- id: ppr:PPR342641
  remove: true

- id: ppr:PPR373963
  remove: true  

- id: doi:10.1101/105262
  remove: true  

- id: doi:10.1101/160184
  remove: true 

- id: doi:10.1101/394205
  remove: true 

- id: doi:10.1101/428615
  remove: true 

- id: doi:10.1101/2024.08.15.24311949
  remove: true 
 

